"""The model library: what "show the engine" can find.

Two lists, merged:
- the seed library that ships with the page (frontend/holo/library.json),
  free sample models loaded from GitHub;
- your own (data/models/catalog.json, gitignored): models saved from the
  page, found online or generated by the forge. Their files sit next to it
  and are served at /models/<file>.

An entry is {id, name, aliases[], src, license?, credit?, about?, parts?}.
"""

from __future__ import annotations

import difflib
import json
import logging
import re
import threading
import time
from pathlib import Path

log = logging.getLogger("jarvis.holo")

ROOT = Path(__file__).resolve().parents[3]
SEED = ROOT / "frontend" / "holo" / "library.json"
USER_DIR = ROOT / "data" / "models"

# Words people wrap a name in: "show me the engine model" -> "engine".
_FILLER = re.compile(r"\b(the|a|an|my|me|show|load|open|model|hologram|holo|3d|of|please)\b")


def _norm(s: str) -> str:
    return re.sub(r"\s+", " ", _FILLER.sub(" ", s.lower().replace("-", " "))).strip()


class ModelCatalog:
    def __init__(self, seed: Path = SEED, user_dir: Path = USER_DIR) -> None:
        self.seed_path = seed
        self.user_dir = user_dir
        self._lock = threading.Lock()

    @property
    def user_path(self) -> Path:
        return self.user_dir / "catalog.json"

    def _read(self, path: Path) -> list[dict]:
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
        except FileNotFoundError:
            return []
        except (OSError, ValueError) as exc:
            log.warning("could not read %s: %s", path, exc)
            return []
        return [m for m in data.get("models", []) if isinstance(m, dict) and m.get("id") and m.get("src")]

    def all(self) -> list[dict]:
        """Yours first, so a model you made wins a name clash with a sample."""
        seen, out = set(), []
        for m in self._read(self.user_path) + self._read(self.seed_path):
            if m["id"] not in seen:
                seen.add(m["id"])
                out.append(m)
        return out

    def get(self, model_id: str) -> dict | None:
        return next((m for m in self.all() if m["id"] == model_id), None)

    def search(self, query: str) -> dict | None:
        """The best match for a spoken name, or None."""
        q = _norm(query)
        if not q:
            return None
        models = self.all()
        names = {}  # normalised name -> entry
        for m in models:
            for n in [m["id"], m.get("name", ""), *m.get("aliases", [])]:
                if n:
                    names.setdefault(_norm(n), m)
        if q in names:
            return names[q]
        # A name inside the request ("the little toy car") or the other way round.
        hits = [(len(n), m) for n, m in names.items() if n and (n in q or q in n)]
        if hits:
            return max(hits, key=lambda h: h[0])[1]
        close = difflib.get_close_matches(q, list(names), n=1, cutoff=0.72)
        return names[close[0]] if close else None

    def add(self, entry: dict) -> dict:
        """Save one of yours; same id replaces the old entry."""
        entry = {k: v for k, v in entry.items() if v not in (None, "", [])}
        entry.setdefault("added", time.strftime("%Y-%m-%d %H:%M"))
        with self._lock:
            self.user_dir.mkdir(parents=True, exist_ok=True)
            mine = [m for m in self._read(self.user_path) if m["id"] != entry["id"]]
            mine.insert(0, entry)
            tmp = self.user_path.with_suffix(".tmp")
            tmp.write_text(json.dumps({"models": mine}, indent=2), encoding="utf-8")
            tmp.replace(self.user_path)
        return entry

    def names(self, limit: int = 12) -> list[str]:
        return [m.get("name") or m["id"] for m in self.all()[:limit]]
